spring:
  profiles:
    active: local
  security:
      user:
       name: user
       password: 1111
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
   level:
     com:
     gongsik:
     gsw: DEBUG