spring:
  profiles: 
    active: local
  security:
      user:
       name: user
       password: 1111
mvc:
  pathmatch:
    matching-strategy: ant_path_matcher
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
   level:
     com:
     gongsik:
     gsw: INFO
     org:
#      hibernate:
#        orm.jdbc.bind: trace
#        SQL: debug

        # Disable p6spy
#decorator:
#  datasource:
#    p6spy:
#      enable-logging: false

---
# Add p6spy profile
#
#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#springdoc:
#  api-docs:
#    path: /api-docs
springdoc:
 default-consumes-media-type: application/json 
 default-produces-media-type: application/json 